export enum TErrors {
  CLOUDFLARE = 'CLOUDFLARE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  GOOGLE_PROVIDER_DID_NOT_RESPOND = 'GOOGLE_PROVIDER_DID_NOT_RESPOND',
  UNKNOWN_PORT_MESSAGE = 'UNKNOWN_PORT_MESSAGE',
  UNKNOWN = 'UNKNOWN',
}
